FROM postgres:latest
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD itssecret
# Copy initialization scripts
COPY init_databases.sh /docker-entrypoint-initdb.d/
COPY simulateur.sql /sql_scripts/
COPY simulateur_DATA.sql /sql_scripts/
COPY emergency.sql /sql_scripts/
# Make sure the initialization script is executable
COPY init_databases.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init_databases.sh
