version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: always
    volumes:
      - ./mosquitto/utils:/mosquitto/utils
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/influxdb:/var/lib/influxdb
      - ./influxdb/influxdb2:/var/lib/influxdb2
      - ./influxdb/influxdb2-utils:/etc/influxdb2
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_V2_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_V2_BUCKET}
volumes:
  config:
  data:
  log: