version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: always
#    network_mode: "host"
    user: 1000:1000
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/utils:/mosquitto/utils:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    ports:
      - "1883:1883"
      - "9001:9001"
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/influxdb:/var/lib/influxdb:rw
      - ./influxdb/influxdb2:/var/lib/influxdb2:rw
      - ./influxdb/influxdb2-utils:/etc/influxdb2:rw
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_V2_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_V2_BUCKET}
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "0"
    # environment:
    # - GF_DATABASE_TYPE=mysql
    # - GF_DATABASE_HOST=db
    # - GF_DATABASE_PORT=3306
    # - GF_DATABASE_NAME=microbit
    # - GF_DATABASE_USER=root
    # - GF_DATABASE_PASSWORD=admin
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/data:/var/lib/grafana
      # - ./grafana/conf:/etc/grafana
    # networks:
    #   iothub: 
    #     ipv4_address: "192.168.80.3"
volumes:
  #config:
  #data:
  #log:
  mosquitto:
  influxdb:
  grafana: