---
topics:
  simulator-view.sensor-changed: "/simulator_view/sensor_changed"
  simulator-view.fire-event: "/simulator_view/fire_event"
  simulator.auto-fire-event: "/simulator/auto_fire_event"
  simulator.new-sensor-value: "/simulator/new_sensor_value"
  rf2.fire-event: "/rf2/fire_event"
  actor.fire-validation: "/actor/fire_validation"
  manager.intervention: "/manager/intervention"
  manager.fire-event-finished: "/manager/fire_event_finished"
